#!/bin/bash
# Get the directory where the AppImage is located
APPDIR="$(dirname "$0")"
export PATH="$APPDIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
export PYTHONPATH="$APPDIR/usr/lib/python3.10/site-packages:$PYTHONPATH"

# Run the application
"$APPDIR/usr/bin/whispertrigger" "$@"
